name: Upload Python package to PyPI when a tagged release is created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/CO2Br/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel 
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 